### ISSUE TITLE
Cldr.List.intersperse

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-cldr/cldr_lists#1]
I'm wondering if we could have something similar to `Enum.intersperse` for `Cldr.List`. Currently we can only work with lists of contents, which can be cast to strings. For phoenix stuff it would be nice to also be able to handle lists like:

```
[{:safe, "some_html_a"}, {:safe, "some_html_b"}, {:safe, "some_html_c"}] =>
[{:safe, "some_html_a"}, ", ", {:safe, "some_html_b"}, " and ", {:safe, "some_html_c"}]
```

**Comment by kipcole9** [comment]
Makes sense, I'll work on that on the weekend.

**Comment by LostKobrakai** [comment]
I've created #2. There's still stuff to be done on the cldr side of things though.

**Comment by kipcole9** [comment]
Cldr lists [version 2.0](https://hex.pm/packages/ex_cldr_lists/2.0.0) is now published and incorporates:
1. Fixed version of `Cldr.Substitution.substitute/2` that works correctly on a list of arbitrary terms.  This is [ex_cldr version 2.0.2](https://hex.pm/packages/ex_cldr/2.0.2).
2. Updated `Cldr.List.intersperse/2` to use `Cldr.Substitution.substitute/2`
3. Refactored `Cldr.List.to_string/2` to use `Cldr.List.intersperse.2`
