### ISSUE TITLE
Old link in GitHub project's description

### ISSUE THREAD

**Issue by petrus-jvrensburg** [elixir-cldr/cldr_lists#6]
<img width="509" alt="Screenshot 2023-08-29 at 09 52 17" src="https://github.com/elixir-cldr/cldr_lists/assets/3660183/49755aa2-c560-4d99-8c2c-0a5bfeba60b5">

👆This should probably point to https://github.com/elixir-cldr/cldr

**Comment by kipcole9** [comment]
I fixed an outdated reference in the readme but the project description doesn't include this link so I'm not sure why it's showing on hex. Nevertheless I will push a docs update now.

Thanks for the report.
